// Influence library — the artists and producers who define the sounds MELAOS
// generates in, drawn from best-selling and most-influential lists across the
// Latin and American markets.
//
// HOW THIS IS USED
// A name is a way to *select* a sound, never an instruction to imitate a
// person. `tag` holds sonic characteristics only — instrumentation, rhythm,
// production era, arrangement — because that is what actually steers the
// music model, and because generating "a copy of <living artist>" is not
// something this platform should offer. No entry asks for a specific voice,
// and the lyric writer is told to borrow craft, never words.
//
// `tag`   → appended to the music model's style tags
// `style` → human description; shown in the picker and given to the songwriter
// `genres`→ which studio genres this influence is offered for

export type InfluenceRole = 'artist' | 'producer';
export type InfluenceRegion = 'Latin' | 'American';

export interface Influence {
  name: string;
  role: InfluenceRole;
  region: InfluenceRegion;
  genres: string[];
  era: string;
  style: string;
  tag: string;
}

export const INFLUENCES: Influence[] = [
  // ── Latin · Tropical roots ────────────────────────────────────────────────
  { name: 'Juan Luis Guerra', role: 'artist', region: 'Latin', genres: ['Merengue', 'Bachata'], era: '1980s–present',
    style: 'Literary merengue and bachata with jazz harmony and big-band horns',
    tag: 'merengue and bachata fusion, jazz-informed harmony, bright horn section, tambora and güira, sophisticated arrangement' },
  { name: 'Romeo Santos', role: 'artist', region: 'Latin', genres: ['Bachata'], era: '2000s–present',
    style: 'Urban bachata crossover — romantic phrasing over modern R&B production',
    tag: 'modern urban bachata, requinto lead lines, romantic minor-key melody, R&B-influenced production, bongo and güira' },
  { name: 'Aventura', role: 'artist', region: 'Latin', genres: ['Bachata'], era: '1990s–2010s',
    style: 'The group that took bachata from countryside to arena',
    tag: 'bachata with hip-hop swing, electric requinto, syncopated bass, streetwise romantic arrangement' },
  { name: 'Frank Reyes', role: 'artist', region: 'Latin', genres: ['Bachata'], era: '1990s–present',
    style: 'Traditional heartbreak bachata, guitar-forward',
    tag: 'classic bachata, weeping requinto guitar, bolero-rooted bassline, melancholic minor key, bongo and güira' },
  { name: 'Luis Vargas', role: 'artist', region: 'Latin', genres: ['Bachata'], era: '1980s–present',
    style: 'Raw countryside bachata, one of the first to electrify the guitar',
    tag: 'raw traditional bachata, electric guitar arpeggios, rustic amargue feel, sparse percussion' },
  { name: 'Johnny Ventura', role: 'artist', region: 'Latin', genres: ['Merengue'], era: '1960s–2000s',
    style: 'Showman merengue — fast, brassy, built for the dance floor',
    tag: 'classic merengue, driving tambora two-step, punchy brass stabs, güira scraper, festive tempo' },
  { name: 'Wilfrido Vargas', role: 'artist', region: 'Latin', genres: ['Merengue'], era: '1970s–1990s',
    style: 'Experimental merengue with Caribbean and pop fusion',
    tag: 'merengue with tropical fusion, bold horn lines, fast güira, playful arrangement' },
  { name: 'Elvis Crespo', role: 'artist', region: 'Latin', genres: ['Merengue'], era: '1990s–present',
    style: 'Explosive merengue pop with an unmistakable hook sensibility',
    tag: 'merengue pop, high-energy horns, rapid güira, anthemic singalong hook' },
  { name: 'Celia Cruz', role: 'artist', region: 'Latin', genres: ['Salsa'], era: '1950s–2000s',
    style: 'The Queen of Salsa — commanding, joyful, Afro-Cuban to the core',
    tag: 'classic Afro-Cuban salsa, montuno piano, full brass section, congas and timbales, call-and-response coro' },
  { name: 'Héctor Lavoe', role: 'artist', region: 'Latin', genres: ['Salsa'], era: '1960s–1990s',
    style: 'Salsa dura with barrio storytelling and razor phrasing',
    tag: 'salsa dura, aggressive brass, driving clave, montuno piano, raw street energy' },
  { name: 'Willie Colón', role: 'artist', region: 'Latin', genres: ['Salsa'], era: '1960s–present',
    style: 'Trombone-led salsa with cinematic, confrontational arrangements',
    tag: 'trombone-forward salsa, hard clave, bold horn arrangement, Afro-Caribbean percussion' },
  { name: 'Rubén Blades', role: 'artist', region: 'Latin', genres: ['Salsa'], era: '1970s–present',
    style: 'Narrative salsa — social storytelling over sophisticated arrangements',
    tag: 'narrative salsa, sophisticated horn writing, montuno piano, storytelling cadence, Latin jazz harmony' },
  { name: 'Tito Puente', role: 'artist', region: 'Latin', genres: ['Salsa'], era: '1940s–2000s',
    style: 'Mambo and Latin jazz built on virtuoso timbales',
    tag: 'mambo and Latin jazz, virtuoso timbales, big-band brass, Afro-Cuban percussion breaks' },
  { name: 'El Gran Combo', role: 'artist', region: 'Latin', genres: ['Salsa'], era: '1960s–present',
    style: 'Puerto Rico’s university of salsa — tight, joyful, relentless',
    tag: 'classic salsa orchestra, tight coro harmonies, bright brass, dance-floor tempo' },
  { name: 'Carlos Vives', role: 'artist', region: 'Latin', genres: ['Cumbia'], era: '1990s–present',
    style: 'Vallenato and cumbia modernised for pop radio',
    tag: 'modern vallenato cumbia, accordion lead, guacharaca scraper, warm coastal groove' },

  // ── Latin · Pop, rock and crossover ───────────────────────────────────────
  { name: 'Shakira', role: 'artist', region: 'Latin', genres: ['Pop', 'Latin Trap', 'Reggaeton'], era: '1990s–present',
    style: 'Global Latin pop with rock edge and Middle-Eastern colour',
    tag: 'Latin pop with rock guitars, Middle-Eastern melodic ornaments, percussive dance groove, anthemic chorus' },
  { name: 'Juan Gabriel', role: 'artist', region: 'Latin', genres: ['Pop'], era: '1970s–2010s',
    style: 'Grand Mexican balladry — mariachi drama and total emotional commitment',
    tag: 'Mexican ballad, mariachi strings and trumpets, dramatic dynamic swells, ranchera phrasing' },
  { name: 'Luis Miguel', role: 'artist', region: 'Latin', genres: ['Pop'], era: '1980s–present',
    style: 'Bolero and orchestral Latin pop, immaculately produced',
    tag: 'orchestral Latin pop bolero, lush strings, big-band swing, romantic crooner arrangement' },
  { name: 'Marc Anthony', role: 'artist', region: 'Latin', genres: ['Salsa', 'Pop'], era: '1990s–present',
    style: 'Salsa romántica with soaring pop delivery',
    tag: 'salsa romántica, soaring melodic lines, lush brass, montuno piano, polished modern production' },
  { name: 'Gloria Estefan', role: 'artist', region: 'Latin', genres: ['Pop', 'Salsa'], era: '1980s–present',
    style: 'Miami sound — Latin percussion inside radio pop',
    tag: 'Miami Latin pop, congas inside pop production, bright horn hooks, crossover polish' },
  { name: 'Julio Iglesias', role: 'artist', region: 'Latin', genres: ['Pop'], era: '1960s–present',
    style: 'The best-selling Latin artist ever — intimate orchestral romance',
    tag: 'orchestral romantic ballad, nylon guitar, sweeping strings, intimate crooner delivery' },
  { name: 'Selena', role: 'artist', region: 'Latin', genres: ['Cumbia', 'Pop'], era: '1980s–1990s',
    style: 'Tejano-cumbia pop, warm and irresistibly danceable',
    tag: 'Tejano cumbia pop, accordion and synth blend, mid-tempo dance groove, bright warm production' },
  { name: 'Vicente Fernández', role: 'artist', region: 'Latin', genres: ['Pop'], era: '1960s–2010s',
    style: 'Ranchera at full voice, mariachi in full dress',
    tag: 'ranchera mariachi, trumpet and violin sections, rubato dramatic phrasing, proud declamatory feel' },
  { name: 'Carlos Santana', role: 'artist', region: 'Latin', genres: ['Latin Trap', 'Pop'], era: '1960s–present',
    style: 'Latin rock — singing guitar over Afro-Cuban percussion',
    tag: 'Latin rock, sustained melodic electric guitar, congas and timbales, blues-rock harmony' },
  { name: 'Roberto Carlos', role: 'artist', region: 'Latin', genres: ['Pop'], era: '1960s–present',
    style: 'Brazilian romantic pop, vast catalogue, timeless melody',
    tag: 'Brazilian romantic pop ballad, warm strings, gentle bossa-tinged rhythm, melodic songcraft' },

  // ── Latin · Urban ─────────────────────────────────────────────────────────
  { name: 'Daddy Yankee', role: 'artist', region: 'Latin', genres: ['Reggaeton', 'Dembow'], era: '1990s–present',
    style: 'The blueprint for global reggaeton',
    tag: 'classic reggaeton, hard dembow riddim, punchy synth stabs, chant-ready hook, club-tuned low end' },
  { name: 'Bad Bunny', role: 'artist', region: 'Latin', genres: ['Reggaeton', 'Latin Trap', 'Dembow'], era: '2010s–present',
    style: 'Genre-blurring Latin urban — trap, reggaeton, and island rhythms',
    tag: 'modern Latin urban, hazy atmospheric synths, dembow and trap hybrid drums, deep sub bass, laid-back pocket' },
  { name: 'J Balvin', role: 'artist', region: 'Latin', genres: ['Reggaeton'], era: '2010s–present',
    style: 'Colourful, minimal, radio-perfect reggaeton',
    tag: 'modern reggaeton, minimal bright synth motifs, clean dembow groove, spacious mix, pop-leaning hook' },
  { name: 'Ozuna', role: 'artist', region: 'Latin', genres: ['Reggaeton'], era: '2010s–present',
    style: 'Melodic reggaeton with a sweet, floating top line',
    tag: 'melodic reggaeton, silky melodic hook, warm synth pads, steady dembow, polished commercial mix' },
  { name: 'Karol G', role: 'artist', region: 'Latin', genres: ['Reggaeton', 'Latin Trap'], era: '2010s–present',
    style: 'Reggaeton with pop craft and confessional edge',
    tag: 'contemporary reggaeton pop, bright melodic hook, crisp dembow, modern polished production' },
  { name: 'Don Omar', role: 'artist', region: 'Latin', genres: ['Reggaeton'], era: '2000s–present',
    style: 'Anthemic, theatrical reggaeton',
    tag: 'anthemic reggaeton, dramatic synth leads, heavy dembow, stadium-scale hook' },
  { name: 'Wisin y Yandel', role: 'artist', region: 'Latin', genres: ['Reggaeton'], era: '2000s–present',
    style: 'Duo-driven club reggaeton with hard electronic edges',
    tag: 'club reggaeton, aggressive synth bass, hard dembow, electronic production accents' },
  { name: 'Tego Calderón', role: 'artist', region: 'Latin', genres: ['Reggaeton', 'Dembow'], era: '2000s–present',
    style: 'Afro-Caribbean roots inside reggaeton, rugged and rhythmic',
    tag: 'Afro-Caribbean reggaeton, live percussion textures, bomba and plena accents, gritty low end' },
  { name: 'Ivy Queen', role: 'artist', region: 'Latin', genres: ['Reggaeton'], era: '1990s–present',
    style: 'The Queen of Reggaeton — commanding delivery, classic riddims',
    tag: 'classic reggaeton, assertive rhythmic phrasing, raw dembow, early-2000s production feel' },
  { name: 'Anuel AA', role: 'artist', region: 'Latin', genres: ['Latin Trap'], era: '2010s–present',
    style: 'Latin trap with melodic menace',
    tag: 'Latin trap, sliding 808 bass, sparse dark synths, triplet hi-hats, melodic auto-tuned hook' },
  { name: 'Rauw Alejandro', role: 'artist', region: 'Latin', genres: ['Reggaeton', 'Latin Trap'], era: '2010s–present',
    style: 'Futuristic reggaeton with R&B and synthwave colour',
    tag: 'futuristic reggaeton, retro synth textures, R&B chord movement, crisp dembow, dance-leaning groove' },
  { name: 'Feid', role: 'artist', region: 'Latin', genres: ['Reggaeton'], era: '2010s–present',
    style: 'Hazy, intimate perreo',
    tag: 'atmospheric reggaeton perreo, hazy reverb-washed synths, soft dembow, intimate late-night mood' },
  { name: 'Natti Natasha', role: 'artist', region: 'Latin', genres: ['Reggaeton', 'Bachata'], era: '2010s–present',
    style: 'Dominican urban pop across reggaeton and bachata',
    tag: 'urban Latin pop, reggaeton and bachata blend, bright melodic hook, modern polished production' },
  { name: 'Peso Pluma', role: 'artist', region: 'Latin', genres: ['Latin Trap'], era: '2020s–present',
    style: 'Corridos tumbados — regional Mexican meets trap attitude',
    tag: 'corridos tumbados, requinto and bajo sexto, tuba bassline, trap-influenced phrasing, sparse arrangement' },
  { name: 'Pitbull', role: 'artist', region: 'Latin', genres: ['Reggaeton', 'Electronic', 'Pop'], era: '2000s–present',
    style: 'Latin club-pop engineered for maximum party',
    tag: 'Latin club pop, four-on-the-floor dance beat, big synth hooks, festival-scale energy' },
  { name: 'Rosalía', role: 'artist', region: 'Latin', genres: ['Latin Trap', 'Pop'], era: '2010s–present',
    style: 'Flamenco tradition fractured through experimental pop',
    tag: 'flamenco-influenced experimental pop, hand claps and palmas, sparse avant-garde production, dramatic vocal phrasing' },

  // ── Latin · Producers ─────────────────────────────────────────────────────
  { name: 'Luny Tunes', role: 'producer', region: 'Latin', genres: ['Reggaeton', 'Dembow'], era: '2000s–present',
    style: 'Dominican duo who built the sound of reggaeton’s breakout era',
    tag: 'golden-era reggaeton production, signature dembow riddim, bright synth lead, sharp percussive layers' },
  { name: 'Tainy', role: 'producer', region: 'Latin', genres: ['Reggaeton', 'Latin Trap'], era: '2000s–present',
    style: 'The architect of modern Latin urban production',
    tag: 'modern Latin urban production, cinematic synth textures, layered percussion, wide atmospheric mix' },
  { name: 'Emilio Estefan', role: 'producer', region: 'Latin', genres: ['Salsa', 'Pop', 'Merengue'], era: '1980s–present',
    style: 'The producer who moved Latin music into the American mainstream',
    tag: 'crossover Latin pop production, polished horn arrangements, Latin percussion inside radio pop' },
  { name: 'Sergio George', role: 'producer', region: 'Latin', genres: ['Salsa', 'Bachata'], era: '1980s–present',
    style: 'Nuyorican salsa production — piano-driven and brass-heavy',
    tag: 'modern salsa production, piano montuno hooks, powerful brass arrangement, crisp tropical percussion' },
  { name: 'Edgar Barrera', role: 'producer', region: 'Latin', genres: ['Reggaeton', 'Pop', 'Cumbia'], era: '2010s–present',
    style: 'Hitmaker across regional Mexican, urban and Latin pop',
    tag: 'contemporary Latin production, hybrid regional and urban arrangement, clean radio-ready mix' },
  { name: 'Nesty', role: 'producer', region: 'Latin', genres: ['Reggaeton'], era: '2000s–present',
    style: 'Melodic reggaeton production with lush harmonic beds',
    tag: 'melodic reggaeton production, lush synth pads, smooth dembow groove, warm harmonic layering' },

  // ── American · Soul, R&B and funk ─────────────────────────────────────────
  { name: 'Michael Jackson', role: 'artist', region: 'American', genres: ['Pop', 'R&B', 'Soul'], era: '1970s–2000s',
    style: 'Pop-funk perfection — rhythm, hooks and arrangement at maximum craft',
    tag: 'pop funk, tight rhythm-section groove, percussive vocal phrasing, layered hooks, immaculate studio polish' },
  { name: 'Stevie Wonder', role: 'artist', region: 'American', genres: ['Soul', 'R&B'], era: '1960s–present',
    style: 'Soul with jazz harmony and irresistible clavinet funk',
    tag: 'classic soul, rich jazz chord movement, clavinet and Rhodes, warm analog groove, live horn section' },
  { name: 'Marvin Gaye', role: 'artist', region: 'American', genres: ['Soul', 'R&B'], era: '1960s–1980s',
    style: 'Sensual, socially aware soul with layered vocal beds',
    tag: 'smooth classic soul, layered vocal harmony, warm bassline, lush strings, mellow groove' },
  { name: 'Aretha Franklin', role: 'artist', region: 'American', genres: ['Soul'], era: '1960s–2010s',
    style: 'Gospel-rooted soul at full power',
    tag: 'gospel soul, church piano, powerful horn section, call-and-response backing vocals' },
  { name: 'Prince', role: 'artist', region: 'American', genres: ['R&B', 'Soul', 'Pop'], era: '1970s–2010s',
    style: 'Funk, rock and R&B fused with total studio control',
    tag: 'funk rock R&B fusion, syncopated drum machine, biting rhythm guitar, synth-bass, adventurous arrangement' },
  { name: 'Whitney Houston', role: 'artist', region: 'American', genres: ['R&B', 'Pop', 'Soul'], era: '1980s–2000s',
    style: 'The gold standard of pop-soul balladry',
    tag: 'pop soul ballad, gospel-informed melodic runs, lush production, dramatic key-change lift' },
  { name: 'Beyoncé', role: 'artist', region: 'American', genres: ['R&B', 'Pop'], era: '1990s–present',
    style: 'Maximalist R&B-pop with precision rhythm and layered vocals',
    tag: 'modern R&B pop, stacked vocal arrangement, hard-hitting percussion, genre-blending production' },
  { name: 'Alicia Keys', role: 'artist', region: 'American', genres: ['R&B', 'Soul'], era: '2000s–present',
    style: 'Piano-led neo-soul with classical grounding',
    tag: 'piano-driven neo soul, live drums, warm chord voicings, soulful melodic phrasing' },
  { name: 'Usher', role: 'artist', region: 'American', genres: ['R&B'], era: '1990s–present',
    style: 'Rhythm-forward contemporary R&B',
    tag: 'contemporary R&B, crisp syncopated drums, smooth melodic hook, polished club-ready mix' },
  { name: 'SZA', role: 'artist', region: 'American', genres: ['R&B'], era: '2010s–present',
    style: 'Hazy, conversational alt-R&B',
    tag: 'alternative R&B, dreamy reverb-soaked textures, loose drum pocket, intimate conversational melody' },
  { name: 'The Weeknd', role: 'artist', region: 'American', genres: ['R&B', 'Pop', 'Electronic'], era: '2010s–present',
    style: 'Dark synth-driven R&B with 80s pop scale',
    tag: 'dark synth R&B, retro 80s synth textures, gated drums, moody atmospheric production' },
  { name: 'Bruno Mars', role: 'artist', region: 'American', genres: ['Pop', 'R&B', 'Soul'], era: '2010s–present',
    style: 'Retro funk and soul rebuilt for modern radio',
    tag: 'retro funk soul, live band feel, tight horn stabs, slap bass, vintage-modern hybrid production' },

  // ── American · Hip-hop ────────────────────────────────────────────────────
  { name: 'Kendrick Lamar', role: 'artist', region: 'American', genres: ['Hip-Hop'], era: '2010s–present',
    style: 'Dense, jazz-inflected, conceptually ambitious hip-hop',
    tag: 'conscious hip-hop, jazz and funk instrumentation, live bass, shifting rhythmic cadence, cinematic arrangement' },
  { name: 'Jay-Z', role: 'artist', region: 'American', genres: ['Hip-Hop'], era: '1990s–present',
    style: 'Soul-sample luxury rap with effortless cadence',
    tag: 'soul-sampling hip-hop, chopped vintage vocal loop, crisp boom bap drums, confident laid-back pocket' },
  { name: 'Nas', role: 'artist', region: 'American', genres: ['Hip-Hop'], era: '1990s–present',
    style: 'Street-poet boom bap with cinematic detail',
    tag: 'boom bap hip-hop, dusty jazz sample, hard-hitting drums, vinyl warmth, narrative pacing' },
  { name: 'The Notorious B.I.G.', role: 'artist', region: 'American', genres: ['Hip-Hop'], era: '1990s',
    style: 'East-coast storytelling over lush, radio-ready loops',
    tag: '90s East Coast hip-hop, soulful sampled loop, thick bassline, crisp snare, smooth swing' },
  { name: '2Pac', role: 'artist', region: 'American', genres: ['Hip-Hop'], era: '1990s',
    style: 'West-coast urgency, melodic funk beds, raw conviction',
    tag: 'West Coast hip-hop, G-funk synth lead, live bass groove, impassioned delivery, warm analog mix' },
  { name: 'Eminem', role: 'artist', region: 'American', genres: ['Hip-Hop'], era: '1990s–present',
    style: 'Technical, dense rhyme construction over hard drums',
    tag: 'technical hip-hop, hard-edged drums, tense minor-key loop, rapid intricate rhythmic phrasing' },
  { name: 'Drake', role: 'artist', region: 'American', genres: ['Hip-Hop', 'R&B'], era: '2000s–present',
    style: 'Melodic rap and R&B blurred into one atmospheric mode',
    tag: 'melodic rap R&B hybrid, ambient synth pads, spacious low end, understated conversational hook' },
  { name: 'Outkast', role: 'artist', region: 'American', genres: ['Hip-Hop'], era: '1990s–2000s',
    style: 'Southern hip-hop with funk, psychedelia and live musicianship',
    tag: 'Southern hip-hop, live funk instrumentation, inventive percussion, psychedelic soul textures' },
  { name: 'Lauryn Hill', role: 'artist', region: 'American', genres: ['Hip-Hop', 'Soul', 'R&B'], era: '1990s–present',
    style: 'Soul, reggae and hip-hop woven together',
    tag: 'soulful hip-hop, reggae-tinged groove, warm live instrumentation, gospel-informed harmony' },
  { name: 'Missy Elliott', role: 'artist', region: 'American', genres: ['Hip-Hop', 'R&B'], era: '1990s–present',
    style: 'Futuristic, playful, rhythmically inventive',
    tag: 'futuristic hip-hop R&B, off-kilter drum programming, bouncy synth hooks, inventive negative space' },

  // ── American · Rock, country, folk ────────────────────────────────────────
  { name: 'Bob Dylan', role: 'artist', region: 'American', genres: ['Pop'], era: '1960s–present',
    style: 'Poetic folk narrative, plainspoken and unhurried',
    tag: 'folk rock, acoustic guitar and harmonica, storytelling cadence, sparse organic arrangement' },
  { name: 'Bruce Springsteen', role: 'artist', region: 'American', genres: ['Pop'], era: '1970s–present',
    style: 'Heartland rock epics about working life',
    tag: 'heartland rock, driving drums, glockenspiel and saxophone, anthemic Americana build' },
  { name: 'Elvis Presley', role: 'artist', region: 'American', genres: ['Pop'], era: '1950s–1970s',
    style: 'Rock and roll’s original crossover of blues, country and gospel',
    tag: 'classic rock and roll, slapback echo, upright bass, twangy guitar, gospel backing vocals' },
  { name: 'Fleetwood Mac', role: 'artist', region: 'American', genres: ['Pop'], era: '1970s–present',
    style: 'Sun-bleached soft rock built on interlocking harmony',
    tag: 'soft rock, layered vocal harmony, clean electric guitar, steady mid-tempo groove, warm 70s mix' },
  { name: 'Dolly Parton', role: 'artist', region: 'American', genres: ['Pop'], era: '1960s–present',
    style: 'Country songcraft — plain language, unforgettable melody',
    tag: 'classic country, acoustic guitar and fiddle, pedal steel, clear narrative melody' },
  { name: 'Johnny Cash', role: 'artist', region: 'American', genres: ['Pop'], era: '1950s–2000s',
    style: 'Stark country with a freight-train rhythm',
    tag: 'outlaw country, boom-chicka rhythm, baritone-range melody, spare stark arrangement' },
  { name: 'Taylor Swift', role: 'artist', region: 'American', genres: ['Pop'], era: '2000s–present',
    style: 'Confessional narrative pop with bridge-first songcraft',
    tag: 'narrative pop, layered acoustic and synth textures, memorable bridge lift, intimate detailed lyricism' },
  { name: 'Madonna', role: 'artist', region: 'American', genres: ['Pop', 'Electronic'], era: '1980s–present',
    style: 'Dance-pop reinvention, decade after decade',
    tag: 'dance pop, four-on-the-floor groove, bright synth hooks, club-ready production' },
  { name: 'Rihanna', role: 'artist', region: 'American', genres: ['Pop', 'R&B'], era: '2000s–present',
    style: 'Caribbean-inflected pop with an edge',
    tag: 'pop with dancehall influence, syncopated riddim, sparse modern production, cool detached hook' },
  { name: 'Frank Sinatra', role: 'artist', region: 'American', genres: ['Soul', 'Pop'], era: '1940s–1990s',
    style: 'Big-band crooning with impeccable phrasing',
    tag: 'big band swing, lush orchestral arrangement, brushed drums, crooner phrasing, vintage warmth' },

  // ── American · Producers ──────────────────────────────────────────────────
  { name: 'Quincy Jones', role: 'producer', region: 'American', genres: ['Pop', 'Soul', 'R&B'], era: '1950s–2020s',
    style: 'Jazz, pop, funk and soul arranged with orchestral command',
    tag: 'lush multi-genre production, full orchestral and horn arrangement, funk rhythm section, pristine studio balance' },
  { name: 'Dr. Dre', role: 'producer', region: 'American', genres: ['Hip-Hop'], era: '1980s–present',
    style: 'G-funk and beyond — immaculate low end, live-feel instrumentation',
    tag: 'G-funk hip-hop production, deep clean bassline, live-feel keys and guitar, spacious polished mix' },
  { name: 'Rick Rubin', role: 'producer', region: 'American', genres: ['Hip-Hop', 'Pop'], era: '1980s–present',
    style: 'Radical subtraction — strip a song to its essential parts',
    tag: 'minimal stripped-back production, dry punchy drums, raw performance forward, uncluttered arrangement' },
  { name: 'Timbaland', role: 'producer', region: 'American', genres: ['Hip-Hop', 'R&B', 'Pop'], era: '1990s–present',
    style: 'Off-kilter rhythm and unexpected sonic sources',
    tag: 'futuristic rhythm production, syncopated stuttering drums, world-percussion textures, deep sub bass' },
  { name: 'The Neptunes', role: 'producer', region: 'American', genres: ['Hip-Hop', 'R&B', 'Pop'], era: '1990s–present',
    style: 'Sparse, sample-less funk built on space and snap',
    tag: 'minimalist funk production, crisp finger snaps and claps, sparse synth stabs, wide-open space in the mix' },
  { name: 'Kanye West', role: 'producer', region: 'American', genres: ['Hip-Hop', 'Soul'], era: '2000s–present',
    style: 'Pitched soul samples and maximal orchestral drama',
    tag: 'soul-sample hip-hop production, pitched-up vocal chop, layered strings, grand dramatic arrangement' },
  { name: 'J Dilla', role: 'producer', region: 'American', genres: ['Hip-Hop', 'Soul'], era: '1990s–2000s',
    style: 'Drunken, humanised drum swing',
    tag: 'off-grid swung drum programming, dusty soul sample, warm saturated low end, unquantised human feel' },
  { name: 'DJ Premier', role: 'producer', region: 'American', genres: ['Hip-Hop'], era: '1990s–present',
    style: 'Boom bap with scratched-in hooks',
    tag: 'boom bap production, hard crackling drums, chopped jazz sample, turntable scratch hook' },
  { name: 'Pete Rock', role: 'producer', region: 'American', genres: ['Hip-Hop', 'Soul'], era: '1990s–present',
    style: 'Horn-drenched, musically rich boom bap',
    tag: 'soulful boom bap, warm horn sample, deep filtered bassline, laid-back drum swing' },
  { name: 'Metro Boomin', role: 'producer', region: 'American', genres: ['Trap', 'Hip-Hop'], era: '2010s–present',
    style: 'Cinematic modern trap',
    tag: 'cinematic trap production, ominous synth melody, sliding 808 bass, rolling hi-hat triplets, wide dark mix' },
  { name: 'Mustard', role: 'producer', region: 'American', genres: ['Hip-Hop', 'Trap'], era: '2010s–present',
    style: 'Bouncy West-coast minimalism',
    tag: 'ratchet West Coast production, bouncy minimal synth line, clap-driven groove, sparse arrangement' },
  { name: 'Noah "40" Shebib', role: 'producer', region: 'American', genres: ['R&B', 'Hip-Hop'], era: '2000s–present',
    style: 'Submerged, nocturnal atmospheres',
    tag: 'ambient nocturnal production, submerged filtered samples, muted drums, deep spacious low end' },
  { name: 'Max Martin', role: 'producer', region: 'American', genres: ['Pop'], era: '1990s–present',
    style: 'Pop architecture — melodic math and airtight structure',
    tag: 'polished radio pop production, tight melodic hook, punchy compressed drums, airtight song structure' },
  { name: 'Nile Rodgers', role: 'producer', region: 'American', genres: ['Soul', 'Pop', 'Electronic'], era: '1970s–present',
    style: 'Disco-funk rhythm guitar as the engine of the record',
    tag: 'disco funk production, chanky rhythm guitar, driving four-on-the-floor groove, string stabs, live bass' },
  { name: 'Giorgio Moroder', role: 'producer', region: 'American', genres: ['Electronic', 'Pop'], era: '1970s–present',
    style: 'The synthesizer as the whole band',
    tag: 'synth disco production, pulsing arpeggiated bassline, analog synth textures, hypnotic four-on-the-floor' },
  { name: 'Swizz Beatz', role: 'producer', region: 'American', genres: ['Hip-Hop'], era: '1990s–present',
    style: 'Loud, triumphant, arena-scale hip-hop',
    tag: 'anthemic hip-hop production, bold synth fanfare, hard kick and snare, chant-ready energy' },
  { name: 'Babyface', role: 'producer', region: 'American', genres: ['R&B', 'Soul'], era: '1980s–present',
    style: 'Silken R&B balladry with impeccable chord movement',
    tag: 'smooth R&B production, warm electric piano, gentle programmed drums, lush romantic harmony' },
  { name: 'Teddy Riley', role: 'producer', region: 'American', genres: ['R&B', 'Hip-Hop'], era: '1980s–present',
    style: 'New jack swing — hip-hop drums under R&B melody',
    tag: 'new jack swing production, swung hard drum machine, funk stabs, R&B melody over hip-hop rhythm' },

  // -- Deep dive: second wave ------------------------------------------
  { name: 'Los Tigres del Norte', role: 'artist', region: 'Latin', genres: ['Cumbia'], era: '1960s-present',
    style: 'Norteno storytelling - the corrido as journalism',
    tag: 'nortena corrido, accordion and bajo sexto, polka-rooted rhythm, narrative pacing' },
  { name: 'Ramon Ayala', role: 'artist', region: 'Latin', genres: ['Cumbia'], era: '1960s-present',
    style: 'The king of the accordion, nortena romance',
    tag: 'nortena, virtuoso accordion lead, bajo sexto, waltz and polka rhythms, warm cantina feel' },
  { name: 'Jose Alfredo Jimenez', role: 'artist', region: 'Latin', genres: ['Pop'], era: '1950s-1970s',
    style: 'The songbook of Mexican heartbreak',
    tag: 'ranchera, mariachi trumpets and violins, rubato dramatic phrasing, cantina melancholy' },
  { name: 'Pedro Infante', role: 'artist', region: 'Latin', genres: ['Pop'], era: '1940s-1950s',
    style: 'Golden-age mariachi romance',
    tag: 'golden-age mariachi, lush trumpet and violin, classic bolero ranchero, vintage warmth' },
  { name: 'Alejandro Fernandez', role: 'artist', region: 'Latin', genres: ['Pop'], era: '1990s-present',
    style: 'Mariachi tradition with pop-ballad polish',
    tag: 'modern mariachi ballad, sweeping strings, trumpet flourishes, polished romantic production' },
  { name: 'Christian Nodal', role: 'artist', region: 'Latin', genres: ['Pop', 'Latin Trap'], era: '2010s-present',
    style: 'Mariacheno - mariachi horns over nortena structure',
    tag: 'mariacheno, mariachi trumpet with nortena accordion, modern clean production, romantic phrasing' },
  { name: 'Natanael Cano', role: 'artist', region: 'Latin', genres: ['Latin Trap'], era: '2010s-present',
    style: 'Corridos tumbados - the trap attitude in regional Mexican',
    tag: 'corridos tumbados, requinto and bajo sexto, tuba bass, trap-influenced cadence, sparse mix' },
  { name: 'Grupo Frontera', role: 'artist', region: 'Latin', genres: ['Cumbia'], era: '2020s-present',
    style: 'Nortena-cumbia reworked for streaming pop',
    tag: 'cumbia nortena, accordion hooks, mid-tempo dance groove, modern radio production' },
  { name: 'Banda MS', role: 'artist', region: 'Latin', genres: ['Pop'], era: '2000s-present',
    style: 'Sinaloan banda at full brass power',
    tag: 'banda sinaloense, full brass and tuba section, snare-driven march, romantic melody' },
  { name: 'Grupo Firme', role: 'artist', region: 'Latin', genres: ['Pop'], era: '2010s-present',
    style: 'Banda and nortena with party-forward swagger',
    tag: 'modern banda, big brass arrangement, tuba bassline, festive singalong energy' },
  { name: 'Antonio Carlos Jobim', role: 'artist', region: 'Latin', genres: ['Pop', 'Soul'], era: '1950s-1990s',
    style: 'The father of bossa nova - jazz harmony, ocean calm',
    tag: 'bossa nova, nylon-string guitar, soft brushed drums, lush jazz chord voicings, gentle sway' },
  { name: 'Joao Gilberto', role: 'artist', region: 'Latin', genres: ['Pop'], era: '1950s-2010s',
    style: 'The whispered voice and syncopated guitar that defined bossa',
    tag: 'intimate bossa nova, syncopated nylon guitar, hushed close-mic delivery, minimal arrangement' },
  { name: 'Caetano Veloso', role: 'artist', region: 'Latin', genres: ['Pop'], era: '1960s-present',
    style: 'Tropicalia - Brazilian tradition through psychedelic pop',
    tag: 'tropicalia, Brazilian acoustic guitar, psychedelic textures, unconventional arrangement' },
  { name: 'Gilberto Gil', role: 'artist', region: 'Latin', genres: ['Pop', 'Reggae'], era: '1960s-present',
    style: 'Afro-Brazilian rhythm fused with reggae and rock',
    tag: 'Afro-Brazilian fusion, samba and reggae rhythms, bright acoustic guitar, layered percussion' },
  { name: 'Elis Regina', role: 'artist', region: 'Latin', genres: ['Soul', 'Pop'], era: '1960s-1980s',
    style: 'MPB at maximum emotional intensity',
    tag: 'MPB, dynamic orchestral arrangement, samba-jazz rhythm section, dramatic vocal build' },
  { name: 'Sergio Mendes', role: 'artist', region: 'Latin', genres: ['Pop', 'Soul'], era: '1960s-2020s',
    style: 'Brazilian jazz-pop built for international radio',
    tag: 'Brazilian jazz pop, bossa piano, bright vocal harmony, samba percussion, sunny arrangement' },
  { name: 'Anitta', role: 'artist', region: 'Latin', genres: ['Reggaeton', 'Pop'], era: '2010s-present',
    style: 'Funk carioca meeting global pop',
    tag: 'Brazilian funk pop, baile funk rhythm, punchy percussion, club-tuned production' },
  { name: 'Oscar D\'Leon', role: 'artist', region: 'Latin', genres: ['Salsa'], era: '1970s-present',
    style: 'El Sonero del Mundo - bass-led salsa with endless improvisation',
    tag: 'classic salsa, prominent bass groove, montuno piano, brass section, improvisational soneo feel' },
  { name: 'Gilberto Santa Rosa', role: 'artist', region: 'Latin', genres: ['Salsa'], era: '1980s-present',
    style: 'Salsa romantica with orchestral elegance',
    tag: 'salsa romantica, refined brass arrangement, montuno piano, smooth mid-tempo groove' },
  { name: 'Frankie Ruiz', role: 'artist', region: 'Latin', genres: ['Salsa'], era: '1980s-1990s',
    style: 'Salsa romantica with raw emotional grain',
    tag: 'salsa romantica, warm brass, expressive phrasing, classic tropical percussion' },
  { name: 'Grupo Niche', role: 'artist', region: 'Latin', genres: ['Salsa'], era: '1980s-present',
    style: 'Colombian salsa with intricate horn writing',
    tag: 'Colombian salsa, intricate horn lines, driving clave, piano montuno, dance-floor tempo' },
  { name: 'Joe Arroyo', role: 'artist', region: 'Latin', genres: ['Salsa', 'Cumbia'], era: '1970s-2010s',
    style: 'Afro-Colombian salsa and tropical fusion',
    tag: 'Afro-Colombian tropical salsa, layered percussion, bright brass, festive groove' },
  { name: 'Prince Royce', role: 'artist', region: 'Latin', genres: ['Bachata'], era: '2010s-present',
    style: 'Bilingual bachata pop for a crossover audience',
    tag: 'modern bachata pop, clean requinto lines, bilingual phrasing, polished radio production' },
  { name: 'Antony Santos', role: 'artist', region: 'Latin', genres: ['Bachata'], era: '1990s-present',
    style: 'El Mayimbe - bachata tipica with virtuoso guitar',
    tag: 'traditional bachata, virtuoso requinto guitar, guira and bongo, rustic amargue feel' },
  { name: 'Zacarias Ferreira', role: 'artist', region: 'Latin', genres: ['Bachata'], era: '1990s-present',
    style: 'Bachata of pure heartbreak, clear and unhurried',
    tag: 'romantic bachata, clean guitar arpeggios, slow tempo, mournful minor-key melody' },
  { name: 'Monchy y Alexandra', role: 'artist', region: 'Latin', genres: ['Bachata'], era: '1990s-2000s',
    style: 'Duet bachata - conversation as song',
    tag: 'duet bachata, interwoven male and female phrasing, bright requinto, classic bachata percussion' },
  { name: 'Ricky Martin', role: 'artist', region: 'Latin', genres: ['Pop', 'Reggaeton'], era: '1990s-present',
    style: 'Latin pop built for stadiums',
    tag: 'Latin pop, big percussion breaks, brass hits, anthemic dance-pop chorus' },
  { name: 'Enrique Iglesias', role: 'artist', region: 'Latin', genres: ['Pop', 'Reggaeton'], era: '1990s-present',
    style: 'Romantic Latin pop with club instincts',
    tag: 'Latin dance pop, smooth melodic hook, club-ready production, romantic delivery' },
  { name: 'Jennifer Lopez', role: 'artist', region: 'Latin', genres: ['Pop', 'R&B'], era: '1990s-present',
    style: 'Latin-tinged pop and R&B for the dance floor',
    tag: 'Latin pop R&B, crisp dance rhythm, bright synth hooks, polished commercial mix' },
  { name: 'Alejandro Sanz', role: 'artist', region: 'Latin', genres: ['Pop'], era: '1990s-present',
    style: 'Flamenco-touched Spanish songwriting',
    tag: 'Spanish pop with flamenco colour, nylon guitar, expressive rubato phrasing, warm organic production' },
  { name: 'Nicky Jam', role: 'artist', region: 'Latin', genres: ['Reggaeton'], era: '2000s-present',
    style: 'Melodic reggaeton with a survivor\'s warmth',
    tag: 'melodic reggaeton, warm synth chords, steady dembow, singalong hook' },
  { name: 'Farruko', role: 'artist', region: 'Latin', genres: ['Reggaeton', 'Dembow'], era: '2010s-present',
    style: 'Reggaeton stretched toward dancehall and electronic',
    tag: 'reggaeton with dancehall and electronic edges, driving dembow, bright synth leads' },
  { name: 'Arcangel', role: 'artist', region: 'Latin', genres: ['Latin Trap', 'Reggaeton'], era: '2000s-present',
    style: 'Sharp lyricism across trap and reggaeton',
    tag: 'Latin trap and reggaeton, punchy 808s, sparse dark synths, rhythmic conversational cadence' },
  { name: 'Zion y Lennox', role: 'artist', region: 'Latin', genres: ['Reggaeton'], era: '2000s-present',
    style: 'Harmony-forward classic reggaeton duo',
    tag: 'classic melodic reggaeton, layered duo harmony, warm dembow, catchy hook writing' },
  { name: 'Myke Towers', role: 'artist', region: 'Latin', genres: ['Latin Trap', 'Reggaeton'], era: '2010s-present',
    style: 'Latin trap with a smooth, unhurried flow',
    tag: 'Latin trap, deep sub bass, moody synth pads, relaxed rhythmic phrasing' },
  { name: 'Residente', role: 'artist', region: 'Latin', genres: ['Hip-Hop', 'Reggaeton'], era: '2000s-present',
    style: 'Latin hip-hop with orchestral ambition and political bite',
    tag: 'Latin hip-hop, live orchestral and folk instrumentation, hard drums, dense narrative cadence' },
  { name: 'Bizarrap', role: 'producer', region: 'Latin', genres: ['Latin Trap', 'Electronic', 'Reggaeton'], era: '2010s-present',
    style: 'Session-format producer bridging trap, house and pop',
    tag: 'modern Latin electronic production, punchy synth bass, club rhythm, minimal hooky arrangement' },
  { name: 'DJ Nelson', role: 'producer', region: 'Latin', genres: ['Reggaeton'], era: '1990s-present',
    style: 'One of the founding architects of reggaeton production',
    tag: 'foundational reggaeton production, raw dembow riddim, sampled percussion, underground grit' },
  { name: 'Rafa Pabon', role: 'artist', region: 'Latin', genres: ['Reggaeton'], era: '2010s-present',
    style: 'Melodic Puerto Rican urban with soulful phrasing',
    tag: 'melodic urban reggaeton, soulful melodic lines, warm dembow, contemporary production' },
  { name: 'Mariah Carey', role: 'artist', region: 'American', genres: ['R&B', 'Pop'], era: '1990s-present',
    style: 'Melisma, whistle register, and hip-hop-soul crossover craft',
    tag: 'R&B pop, layered vocal runs, lush harmony beds, hip-hop influenced drum programming' },
  { name: 'Janet Jackson', role: 'artist', region: 'American', genres: ['R&B', 'Pop'], era: '1980s-present',
    style: 'Rhythm-first pop-R&B with industrial precision',
    tag: 'rhythm-driven R&B pop, hard programmed drums, funk bass, percussive vocal arrangement' },
  { name: 'Luther Vandross', role: 'artist', region: 'American', genres: ['R&B', 'Soul'], era: '1980s-2000s',
    style: 'Velvet balladry with immaculate vocal arrangement',
    tag: 'smooth soul ballad, lush layered backing vocals, warm bass, elegant string arrangement' },
  { name: 'Earth, Wind & Fire', role: 'artist', region: 'American', genres: ['Soul', 'R&B'], era: '1970s-present',
    style: 'Cosmic funk with a horn section like a sunrise',
    tag: 'funk soul, powerhouse horn section, tight rhythm guitar, layered harmony, kalimba accents' },
  { name: 'Chaka Khan', role: 'artist', region: 'American', genres: ['Soul', 'R&B'], era: '1970s-present',
    style: 'Funk-soul power with jazz phrasing',
    tag: 'funk soul, driving bassline, horn stabs, virtuosic melodic improvisation' },
  { name: 'Diana Ross', role: 'artist', region: 'American', genres: ['Soul', 'Pop'], era: '1960s-present',
    style: 'Motown elegance into disco glamour',
    tag: 'Motown soul and disco, sweeping strings, steady four-on-the-floor, polished sheen' },
  { name: 'The Temptations', role: 'artist', region: 'American', genres: ['Soul'], era: '1960s-present',
    style: 'Motown harmony and psychedelic soul',
    tag: 'Motown soul, tight five-part harmony, punchy horns, tambourine-driven groove' },
  { name: 'Anita Baker', role: 'artist', region: 'American', genres: ['Soul', 'R&B'], era: '1980s-present',
    style: 'Quiet storm - jazz-inflected, unhurried soul',
    tag: 'quiet storm soul, jazz chord voicings, brushed drums, warm fretless bass, intimate mood' },
  { name: 'Toni Braxton', role: 'artist', region: 'American', genres: ['R&B'], era: '1990s-present',
    style: 'Contralto R&B balladry',
    tag: 'R&B ballad, low warm melodic register, sparse elegant production, lush pads' },
  { name: 'Boyz II Men', role: 'artist', region: 'American', genres: ['R&B', 'Soul'], era: '1990s-present',
    style: 'A cappella-rooted harmony ballads',
    tag: 'R&B harmony ballad, four-part vocal arrangement, gentle programmed drums, warm bass' },
  { name: 'TLC', role: 'artist', region: 'American', genres: ['R&B', 'Hip-Hop'], era: '1990s-2000s',
    style: 'New jack attitude with pop-perfect hooks',
    tag: '90s R&B hip-hop, swung drum programming, funk bass, playful layered hooks' },
  { name: 'Destiny\'s Child', role: 'artist', region: 'American', genres: ['R&B', 'Pop'], era: '1990s-2000s',
    style: 'Rhythmic vocal stacking over hard drums',
    tag: 'R&B pop, intricate stacked harmony, syncopated hard drums, sparse punchy production' },
  { name: 'Wu-Tang Clan', role: 'artist', region: 'American', genres: ['Hip-Hop'], era: '1990s-present',
    style: 'Gritty kung-fu soul, raw and cinematic',
    tag: 'raw 90s hip-hop, dusty soul sample, lo-fi drums, eerie piano loop, cinematic grit' },
  { name: 'A Tribe Called Quest', role: 'artist', region: 'American', genres: ['Hip-Hop'], era: '1990s-2010s',
    style: 'Jazz-rap with an easy, conversational pocket',
    tag: 'jazz rap, upright bass sample, laid-back boom bap drums, warm mellow loop' },
  { name: 'Public Enemy', role: 'artist', region: 'American', genres: ['Hip-Hop'], era: '1980s-present',
    style: 'Dense, sirening, confrontational production',
    tag: 'politically charged hip-hop, dense layered samples, siren textures, hard-hitting funk break' },
  { name: 'Run-DMC', role: 'artist', region: 'American', genres: ['Hip-Hop'], era: '1980s-1990s',
    style: 'Rock-fused hip-hop, stripped to drums and shout',
    tag: 'old school hip-hop, huge drum machine hits, rock guitar riff, call-and-response delivery' },
  { name: 'Snoop Dogg', role: 'artist', region: 'American', genres: ['Hip-Hop'], era: '1990s-present',
    style: 'West coast laid-back drawl over G-funk',
    tag: 'G-funk hip-hop, whining synth lead, deep bassline, relaxed swinging pocket' },
  { name: 'Lil Wayne', role: 'artist', region: 'American', genres: ['Hip-Hop'], era: '2000s-present',
    style: 'Punchline-dense southern rap with melodic instincts',
    tag: 'southern hip-hop, bouncy synth melody, crisp hi-hats, heavy 808 bass' },
  { name: 'Future', role: 'artist', region: 'American', genres: ['Trap', 'Hip-Hop'], era: '2010s-present',
    style: 'Melodic trap haze',
    tag: 'melodic trap, auto-tuned melodic hook, dark atmospheric synths, rolling hi-hats, heavy 808s' },
  { name: 'Travis Scott', role: 'artist', region: 'American', genres: ['Trap', 'Hip-Hop'], era: '2010s-present',
    style: 'Psychedelic, cavernous trap production',
    tag: 'psychedelic trap, cavernous reverb, distorted 808s, layered atmospheric synths, beat switches' },
  { name: 'J. Cole', role: 'artist', region: 'American', genres: ['Hip-Hop'], era: '2010s-present',
    style: 'Introspective, soul-sampling rap',
    tag: 'soulful hip-hop, warm sampled loop, live-feel drums, reflective conversational cadence' },
  { name: 'Nirvana', role: 'artist', region: 'American', genres: ['Pop'], era: '1990s',
    style: 'Grunge - quiet verse, detonating chorus',
    tag: 'grunge rock, distorted guitar, dynamic loud-quiet contrast, raw drum sound' },
  { name: 'Red Hot Chili Peppers', role: 'artist', region: 'American', genres: ['Pop'], era: '1980s-present',
    style: 'Funk-rock built on slap bass',
    tag: 'funk rock, slap bass groove, syncopated guitar, punchy live drums' },
  { name: 'Tina Turner', role: 'artist', region: 'American', genres: ['Soul', 'Pop'], era: '1960s-2010s',
    style: 'Rock-soul at full throttle',
    tag: 'rock soul, driving backbeat, gritty horn stabs, powerhouse delivery' },
  { name: 'Lady Gaga', role: 'artist', region: 'American', genres: ['Pop', 'Electronic'], era: '2000s-present',
    style: 'Theatrical electro-pop with real songcraft underneath',
    tag: 'electropop, big synth hooks, four-on-the-floor, dramatic vocal arrangement' },
  { name: 'Billie Eilish', role: 'artist', region: 'American', genres: ['Pop', 'Electronic'], era: '2010s-present',
    style: 'Whispered intimacy over subterranean bass',
    tag: 'alternative pop, close-mic intimate delivery, deep sub bass, minimal sparse production' },
  { name: 'Post Malone', role: 'artist', region: 'American', genres: ['Hip-Hop', 'Pop'], era: '2010s-present',
    style: 'Melodic rap-pop with guitar warmth',
    tag: 'melodic rap pop, acoustic guitar textures, trap drums, hazy melancholic hook' },
  { name: 'Doja Cat', role: 'artist', region: 'American', genres: ['Pop', 'R&B', 'Hip-Hop'], era: '2010s-present',
    style: 'Genre-hopping pop-rap with funk bounce',
    tag: 'pop rap, funk-inflected bassline, bouncy percussion, playful melodic hook' },
  { name: 'George Martin', role: 'producer', region: 'American', genres: ['Pop', 'Soul'], era: '1950s-2010s',
    style: 'Orchestral imagination applied to pop records',
    tag: 'orchestral pop production, string and brass arrangement, inventive studio texture, clean classic balance' },
  { name: 'Phil Spector', role: 'producer', region: 'American', genres: ['Pop', 'Soul'], era: '1960s-1970s',
    style: 'The Wall of Sound - little symphonies for the kids',
    tag: 'wall of sound production, massed layered instrumentation, heavy reverb, dense monophonic power' },
  { name: 'Berry Gordy', role: 'producer', region: 'American', genres: ['Soul', 'R&B'], era: '1960s-1980s',
    style: 'The Motown assembly line - hooks, handclaps, hit after hit',
    tag: 'Motown production, tambourine and handclap backbeat, melodic bassline, bright horn punctuation' },
  { name: 'Jimmy Iovine', role: 'producer', region: 'American', genres: ['Pop'], era: '1970s-present',
    style: 'Big-canvas rock records with radio instincts',
    tag: 'arena rock production, wide reverb, powerful drum sound, layered guitars' },
  { name: 'Brian Eno', role: 'producer', region: 'American', genres: ['Electronic', 'Pop'], era: '1970s-present',
    style: 'Ambient texture and productive accident',
    tag: 'ambient textured production, atmospheric synth layers, unconventional processing, spacious mix' },
  { name: 'Jam & Lewis', role: 'producer', region: 'American', genres: ['R&B', 'Soul'], era: '1980s-present',
    style: 'Minneapolis funk precision in R&B',
    tag: 'Minneapolis funk R&B production, crisp programmed drums, synth bass, tight percussive arrangement' },
  { name: 'Mark Ronson', role: 'producer', region: 'American', genres: ['Soul', 'Pop', 'R&B'], era: '2000s-present',
    style: 'Vintage soul instrumentation with modern punch',
    tag: 'retro soul production, live horn section, vintage drum sound, warm analog character' },
  { name: 'Jack Antonoff', role: 'producer', region: 'American', genres: ['Pop'], era: '2010s-present',
    style: 'Atmospheric, drum-forward indie pop',
    tag: 'indie pop production, reverb-washed synths, prominent live drums, intimate vocal placement' },
  { name: 'Finneas', role: 'producer', region: 'American', genres: ['Pop', 'Electronic'], era: '2010s-present',
    style: 'Bedroom-scale production with cinematic low end',
    tag: 'minimal bedroom pop production, close intimate vocals, deep sub bass, sparse detailed sound design' },
  { name: 'Hit-Boy', role: 'producer', region: 'American', genres: ['Hip-Hop', 'Trap'], era: '2010s-present',
    style: 'Hard-hitting drums with soulful chord beds',
    tag: 'modern hip-hop production, punchy drums, soulful chord loop, clean powerful low end' },
  { name: 'Mike WiLL Made-It', role: 'producer', region: 'American', genres: ['Trap', 'Hip-Hop'], era: '2010s-present',
    style: 'Trap with menacing melodic hooks',
    tag: 'trap production, ominous melodic synth, hard 808 bass, sharp hi-hat patterns' },
  { name: 'Scott Storch', role: 'producer', region: 'American', genres: ['Hip-Hop', 'R&B'], era: '2000s-present',
    style: 'Piano-led hip-hop with Middle-Eastern colour',
    tag: 'hip-hop production, prominent piano riff, Middle-Eastern melodic scales, crisp club drums' },
  { name: 'RZA', role: 'producer', region: 'American', genres: ['Hip-Hop'], era: '1990s-present',
    style: 'Raw, cinematic soul chops',
    tag: 'gritty hip-hop production, distorted soul sample, lo-fi drums, dark cinematic atmosphere' },
  { name: 'Madlib', role: 'producer', region: 'American', genres: ['Hip-Hop', 'Soul'], era: '1990s-present',
    style: 'Crate-dug loops and unquantised swing',
    tag: 'underground hip-hop production, obscure jazz sample, loose drum swing, lo-fi warmth' },
  { name: 'The Alchemist', role: 'producer', region: 'American', genres: ['Hip-Hop'], era: '1990s-present',
    style: 'Hypnotic loops, minimal drums, heavy mood',
    tag: 'loop-driven hip-hop production, hypnotic sample, sparse drums, dusty atmospheric texture' },
  { name: 'Boi-1da', role: 'producer', region: 'American', genres: ['Hip-Hop', 'R&B'], era: '2000s-present',
    style: 'Spacious modern rap with melodic depth',
    tag: 'modern rap production, spacious mix, melodic synth layers, hard-hitting minimal drums' },
  { name: 'Sounwave', role: 'producer', region: 'American', genres: ['Hip-Hop'], era: '2000s-present',
    style: 'Jazz-literate, structurally adventurous rap production',
    tag: 'experimental hip-hop production, jazz instrumentation, shifting arrangement, live bass' },
  { name: 'Diplo', role: 'producer', region: 'American', genres: ['Electronic', 'Reggaeton', 'Pop'], era: '2000s-present',
    style: 'Global club rhythms folded into pop',
    tag: 'global club production, dancehall and moombahton rhythms, big drop, percussive hooks' },
  { name: 'Calvin Harris', role: 'producer', region: 'American', genres: ['Electronic', 'Pop'], era: '2000s-present',
    style: 'Festival-scale electro-pop',
    tag: 'electro pop production, euphoric synth lead, four-on-the-floor, big-room build and drop' },
  { name: 'Daft Punk', role: 'producer', region: 'American', genres: ['Electronic'], era: '1990s-2020s',
    style: 'French house - filtered disco loops and vocoder',
    tag: 'French house production, filtered disco sample, vocoder textures, driving four-on-the-floor' },
  { name: 'Skrillex', role: 'producer', region: 'American', genres: ['Electronic'], era: '2000s-present',
    style: 'Aggressive sound design and drop-first structure',
    tag: 'bass music production, aggressive modulated synth, heavy drop, intricate sound design' },
  { name: 'Kaytranada', role: 'producer', region: 'American', genres: ['Electronic', 'R&B', 'Soul'], era: '2010s-present',
    style: 'Off-kilter house with soul warmth',
    tag: 'house and soul fusion, swung drum programming, warm filtered chords, deep groovy bass' },
  { name: 'Avicii', role: 'producer', region: 'American', genres: ['Electronic', 'Pop'], era: '2010s-2010s',
    style: 'Folk melody inside progressive house',
    tag: 'progressive house production, melodic piano lead, folk-tinged melody, euphoric build' },

  // -- Deep dive: second wave ------------------------------------------
  { name: 'DJ Luian', role: 'producer', region: 'Latin', genres: ['Reggaeton', 'Latin Trap'], era: '2010s-present',
    style: 'Foundational urbano producer behind a decade of hits',
    tag: 'modern reggaeton production, hard dembow, deep synth bass, polished club-tuned mix' },
  { name: 'Mambo Kingz', role: 'producer', region: 'Latin', genres: ['Reggaeton', 'Latin Trap'], era: '2000s-present',
    style: 'Two decades shaping the Latin urban landscape',
    tag: 'Latin urban production, layered synth arrangement, punchy dembow, wide commercial mix' },
  { name: 'Sky Rompiendo', role: 'producer', region: 'Latin', genres: ['Reggaeton'], era: '2010s-present',
    style: 'Medellin bass weight - basslines pushed to their limit',
    tag: 'Colombian reggaeton production, heavy rolling bassline, crisp dembow, bright melodic synth' },
  { name: 'Ovy on the Drums', role: 'producer', region: 'Latin', genres: ['Reggaeton', 'Latin Trap'], era: '2010s-present',
    style: 'Melody-forward reggaeton with pop instincts',
    tag: 'melodic reggaeton production, catchy synth motif, clean dembow groove, radio-ready polish' },
  { name: 'Chris Jeday', role: 'producer', region: 'Latin', genres: ['Reggaeton'], era: '2010s-present',
    style: 'Genre-blending, melody-led urbano production',
    tag: 'melodic urbano production, lush chord beds, smooth dembow, spacious arrangement' },
  { name: 'Chael Produciendo', role: 'producer', region: 'Latin', genres: ['Dembow', 'Latin Trap'], era: '2010s-present',
    style: 'Architect of trapbow - trap weight on a dembow skeleton',
    tag: 'trapbow production, dembow rhythm with trap 808s, sharp percussion, aggressive low end' },
  { name: 'Nely El Arma Secreta', role: 'producer', region: 'Latin', genres: ['Reggaeton'], era: '2000s-present',
    style: 'Classic-era reggaeton production with cinematic scale',
    tag: 'classic reggaeton production, dramatic synth stabs, hard dembow, dense layered percussion' },
  { name: 'Dimelo Flow', role: 'producer', region: 'Latin', genres: ['Reggaeton', 'Dembow'], era: '2010s-present',
    style: 'Panamanian producer blending reggaeton with Caribbean roots',
    tag: 'Caribbean-leaning reggaeton production, bouncy dembow, bright percussion, warm melodic hooks' },
  { name: 'Marioso', role: 'producer', region: 'Latin', genres: ['Reggaeton', 'Latin Trap'], era: '2010s-present',
    style: 'Contemporary urbano with clean, modern low end',
    tag: 'contemporary urbano production, tight dembow, clean sub bass, minimal synth texture' },
  { name: 'Light GM', role: 'producer', region: 'Latin', genres: ['Dembow'], era: '2010s-present',
    style: 'Dembow production with trap-era edge',
    tag: 'Dominican dembow production, rapid percussive loop, hard kick pattern, raw energetic mix' },
  { name: 'Kike Santander', role: 'producer', region: 'Latin', genres: ['Pop', 'Salsa'], era: '1990s-present',
    style: 'Latin pop songcraft with tropical arrangement instincts',
    tag: 'Latin pop production, lush orchestration, tropical percussion accents, polished radio arrangement' },
  { name: 'Estefano', role: 'producer', region: 'Latin', genres: ['Pop'], era: '1990s-present',
    style: 'Prolific Latin pop songwriting - hooks built to last',
    tag: 'Latin pop ballad production, warm acoustic and string layers, strong melodic hook' },
  { name: 'Rudy Perez', role: 'producer', region: 'Latin', genres: ['Pop'], era: '1980s-present',
    style: 'Latin ballad production with crossover polish',
    tag: 'Latin ballad production, sweeping strings, piano-led arrangement, romantic dynamic build' },
  { name: 'El Alfa', role: 'artist', region: 'Latin', genres: ['Dembow'], era: '2010s-present',
    style: 'The patriarch of Dominican dembow',
    tag: 'Dominican dembow, rapid-fire percussion loop, hard kick, chant-driven hook, raw street energy' },
  { name: 'Rochy RD', role: 'artist', region: 'Latin', genres: ['Dembow'], era: '2010s-present',
    style: 'Street-level dembow with relentless drive',
    tag: 'raw dembow, aggressive percussive loop, minimal melody, high-energy chant' },
  { name: 'Bulin 47', role: 'artist', region: 'Latin', genres: ['Dembow'], era: '2010s-present',
    style: 'Playful, hook-heavy dembow',
    tag: 'dembow, bouncy percussion pattern, catchy chant hook, bright sparse production' },
  { name: 'Hector El Father', role: 'artist', region: 'Latin', genres: ['Reggaeton'], era: '2000s-present',
    style: 'Hard-edged classic reggaeton with cinematic menace',
    tag: 'classic hard reggaeton, dark synth lines, heavy dembow, dramatic arrangement' },
  { name: 'Tito El Bambino', role: 'artist', region: 'Latin', genres: ['Reggaeton'], era: '2000s-present',
    style: 'Romantic reggaeton with tropical warmth',
    tag: 'romantic reggaeton, tropical percussion accents, warm melodic hook, smooth dembow' },
  { name: 'Yandel', role: 'artist', region: 'Latin', genres: ['Reggaeton'], era: '2000s-present',
    style: 'Silky melodic reggaeton',
    tag: 'melodic reggaeton, smooth synth pads, steady dembow, polished vocal-forward mix' },
  { name: 'Jowell y Randy', role: 'artist', region: 'Latin', genres: ['Reggaeton'], era: '2000s-present',
    style: 'Perreo with humour and old-school bounce',
    tag: 'classic perreo reggaeton, bouncy dembow, playful synth hooks, party-driven energy' },
  { name: 'Plan B', role: 'artist', region: 'Latin', genres: ['Reggaeton'], era: '2000s-2010s',
    style: 'Sensual, melodic duo reggaeton',
    tag: 'melodic sensual reggaeton, layered harmony, mid-tempo dembow, warm production' },
  { name: 'De La Ghetto', role: 'artist', region: 'Latin', genres: ['Reggaeton', 'Latin Trap'], era: '2000s-present',
    style: 'Bilingual urbano bridging reggaeton and trap',
    tag: 'bilingual urbano, hybrid dembow and trap drums, melodic hook, modern mix' },
  { name: 'Sech', role: 'artist', region: 'Latin', genres: ['Reggaeton'], era: '2010s-present',
    style: 'Panamanian melodic reggaeton with R&B softness',
    tag: 'melodic reggaeton with R&B texture, warm chords, soft dembow, intimate hook' },
  { name: 'Eladio Carrion', role: 'artist', region: 'Latin', genres: ['Latin Trap'], era: '2010s-present',
    style: 'Latin trap with heavyweight low end',
    tag: 'Latin trap, deep 808 bass, dark cinematic synths, hard triplet hi-hats' },
  { name: 'Young Miko', role: 'artist', region: 'Latin', genres: ['Latin Trap', 'Reggaeton'], era: '2020s-present',
    style: 'New-wave Latin trap with a cool, unhurried edge',
    tag: 'modern Latin trap, sparse hazy synths, punchy 808s, laid-back rhythmic phrasing' },
  { name: 'Alvaro Diaz', role: 'artist', region: 'Latin', genres: ['Latin Trap', 'Reggaeton'], era: '2010s-present',
    style: 'Alt-leaning Puerto Rican urbano',
    tag: 'alternative Latin urban, dreamy synth textures, soft dembow, melodic introspective hook' },
  { name: 'Maluma', role: 'artist', region: 'Latin', genres: ['Reggaeton', 'Pop'], era: '2010s-present',
    style: 'Reggaeton pop with a smooth commercial sheen',
    tag: 'reggaeton pop, silky melodic hook, clean dembow, glossy commercial production' },
  { name: 'Camilo', role: 'artist', region: 'Latin', genres: ['Pop'], era: '2010s-present',
    style: 'Acoustic-leaning Latin pop, warm and intimate',
    tag: 'acoustic Latin pop, nylon guitar, handclap percussion, bright singalong hook' },
  { name: 'Sebastian Yatra', role: 'artist', region: 'Latin', genres: ['Pop', 'Reggaeton'], era: '2010s-present',
    style: 'Romantic Latin pop with urbano rhythm underneath',
    tag: 'Latin pop with reggaeton rhythm, warm melodic hook, polished radio production' },
  { name: 'Manuel Turizo', role: 'artist', region: 'Latin', genres: ['Reggaeton', 'Pop'], era: '2010s-present',
    style: 'Low-register melodic reggaeton pop',
    tag: 'melodic reggaeton pop, warm low melodic register, soft dembow, clean modern mix' },
  { name: 'Juanes', role: 'artist', region: 'Latin', genres: ['Pop'], era: '1990s-present',
    style: 'Colombian rock with vallenato and cumbia in its blood',
    tag: 'Latin rock, electric guitar riffs, cumbia and vallenato rhythm accents, anthemic chorus' },
  { name: 'Bomba Estereo', role: 'artist', region: 'Latin', genres: ['Cumbia', 'Electronic'], era: '2000s-present',
    style: 'Electro-cumbia with Caribbean psychedelia',
    tag: 'electro cumbia, tropical percussion, pulsing electronic bass, psychedelic synth textures' },
  { name: 'Luis Fonsi', role: 'artist', region: 'Latin', genres: ['Pop', 'Reggaeton'], era: '1990s-present',
    style: 'Latin pop balladry that crossed into global urbano',
    tag: 'Latin pop, bright acoustic and synth blend, reggaeton rhythm accents, soaring chorus' },
  { name: 'Chayanne', role: 'artist', region: 'Latin', genres: ['Pop'], era: '1980s-present',
    style: 'Latin pop romance with dance-floor polish',
    tag: 'Latin dance pop, tropical percussion, bright brass accents, romantic melodic delivery' },
  { name: 'Thalia', role: 'artist', region: 'Latin', genres: ['Pop'], era: '1990s-present',
    style: 'Mexican pop with tropical and dance colour',
    tag: 'Latin dance pop, upbeat percussion, bright synth hooks, glossy commercial production' },
  { name: 'Eddie Palmieri', role: 'artist', region: 'Latin', genres: ['Salsa'], era: '1960s-present',
    style: 'Adventurous piano-led Latin jazz and salsa',
    tag: 'Latin jazz salsa, dissonant piano montuno, powerful brass, complex Afro-Cuban percussion' },
  { name: 'Ray Barretto', role: 'artist', region: 'Latin', genres: ['Salsa'], era: '1960s-2000s',
    style: 'Hard hands - conga-driven salsa and Latin jazz',
    tag: 'conga-driven salsa, Latin jazz harmony, tight brass, propulsive Afro-Cuban rhythm' },
  { name: 'Ismael Rivera', role: 'artist', region: 'Latin', genres: ['Salsa'], era: '1950s-1980s',
    style: 'El Sonero Mayor - bomba and plena inside salsa',
    tag: 'bomba and plena salsa, Afro-Puerto Rican percussion, call-and-response coro, syncopated phrasing' },
  { name: 'Cheo Feliciano', role: 'artist', region: 'Latin', genres: ['Salsa'], era: '1950s-2010s',
    style: 'Warm, unhurried salsa and bolero',
    tag: 'salsa and bolero, smooth phrasing, lush brass, relaxed montuno groove' },
  { name: 'Victor Manuelle', role: 'artist', region: 'Latin', genres: ['Salsa'], era: '1990s-present',
    style: 'Modern salsa with improvisational fire',
    tag: 'modern salsa, bright brass arrangement, montuno piano, improvisational soneo passages' },
  { name: 'La India', role: 'artist', region: 'Latin', genres: ['Salsa'], era: '1990s-present',
    style: 'Salsa power with house and soul roots',
    tag: 'salsa with soul phrasing, powerful brass, driving clave, dramatic dynamic build' },
  { name: 'Eddie Santiago', role: 'artist', region: 'Latin', genres: ['Salsa'], era: '1980s-present',
    style: 'Salsa sensual - smooth, romantic, mid-tempo',
    tag: 'salsa sensual, smooth brass, romantic melody, relaxed dance tempo' },
  { name: 'Beny More', role: 'artist', region: 'Latin', genres: ['Salsa'], era: '1940s-1960s',
    style: 'El Barbaro del Ritmo - Cuban son and mambo',
    tag: 'Cuban son and mambo, big-band brass, classic Afro-Cuban percussion, vintage warmth' },
  { name: 'Arsenio Rodriguez', role: 'artist', region: 'Latin', genres: ['Salsa'], era: '1940s-1970s',
    style: 'The architect of the modern conjunto sound',
    tag: 'Cuban son montuno, tres guitar, conga and bongo, horn-driven conjunto arrangement' },
  { name: 'Buena Vista Social Club', role: 'artist', region: 'Latin', genres: ['Salsa'], era: '1990s-2000s',
    style: 'Cuban son revived in full acoustic warmth',
    tag: 'traditional Cuban son, acoustic tres and guitar, upright bass, gentle conga, vintage room sound' },
  { name: 'Los Van Van', role: 'artist', region: 'Latin', genres: ['Salsa'], era: '1960s-present',
    style: 'Songo - Cuban dance music constantly reinvented',
    tag: 'songo Cuban dance music, electric bass groove, violins and trombones, layered percussion' },
  { name: 'Fernando Villalona', role: 'artist', region: 'Latin', genres: ['Merengue'], era: '1970s-present',
    style: 'El Mayimbe - romantic merengue with a big voice',
    tag: 'romantic merengue, warm brass, steady tambora, singalong melodic hook' },
  { name: 'Sergio Vargas', role: 'artist', region: 'Latin', genres: ['Merengue'], era: '1980s-present',
    style: 'Polished merengue with orchestral horn writing',
    tag: 'classic merengue, refined horn arrangement, driving tambora and guira, bright tempo' },
  { name: 'Milly Quezada', role: 'artist', region: 'Latin', genres: ['Merengue'], era: '1970s-present',
    style: 'The Queen of Merengue',
    tag: 'merengue, punchy brass section, fast guira, joyful dance-floor energy' },
  { name: 'Los Hermanos Rosario', role: 'artist', region: 'Latin', genres: ['Merengue'], era: '1970s-present',
    style: 'Merengue built for nonstop movement',
    tag: 'high-energy merengue, relentless tambora, bold horn stabs, festive party arrangement' },
  { name: 'Tono Rosario', role: 'artist', region: 'Latin', genres: ['Merengue'], era: '1980s-present',
    style: 'Merengue with raw showmanship',
    tag: 'merengue, driving two-step tambora, brassy hooks, exuberant delivery' },
  { name: 'Raulin Rodriguez', role: 'artist', region: 'Latin', genres: ['Bachata'], era: '1990s-present',
    style: 'El Cacique - bachata romance with guitar fire',
    tag: 'traditional bachata, bright requinto lead, steady bongo and guira, romantic minor melody' },
  { name: 'Joe Veras', role: 'artist', region: 'Latin', genres: ['Bachata'], era: '1990s-present',
    style: 'Bachata with refined arrangement and clean guitar',
    tag: 'polished bachata, clean requinto arpeggios, warm bass, smooth mid-tempo groove' },
  { name: 'El Chaval de la Bachata', role: 'artist', region: 'Latin', genres: ['Bachata'], era: '1990s-present',
    style: 'Emotive bachata with a soaring melodic line',
    tag: 'romantic bachata, expressive requinto, soaring melodic phrasing, classic bachata percussion' },
  { name: 'Yoskar Sarante', role: 'artist', region: 'Latin', genres: ['Bachata'], era: '1990s-2020s',
    style: 'Bachata of pure amargue',
    tag: 'melancholic bachata, weeping guitar lines, slow tempo, sorrowful minor-key melody' },
  { name: 'Hector Acosta El Torito', role: 'artist', region: 'Latin', genres: ['Bachata', 'Merengue'], era: '1990s-present',
    style: 'Bachata and merengue with a bolero heart',
    tag: 'bachata and merengue blend, warm guitar and brass, romantic bolero phrasing' },
  { name: 'Diomedes Diaz', role: 'artist', region: 'Latin', genres: ['Cumbia'], era: '1970s-2010s',
    style: 'El Cacique de La Junta - vallenato storytelling',
    tag: 'classic vallenato, accordion lead, caja and guacharaca, narrative romantic phrasing' },
  { name: 'Silvestre Dangond', role: 'artist', region: 'Latin', genres: ['Cumbia'], era: '2000s-present',
    style: 'Vallenato modernised with pop energy',
    tag: 'modern vallenato, bright accordion, pop-leaning arrangement, upbeat coastal groove' },
  { name: 'Binomio de Oro', role: 'artist', region: 'Latin', genres: ['Cumbia'], era: '1970s-present',
    style: 'Vallenato with polished ensemble precision',
    tag: 'vallenato, virtuoso accordion, tight percussion, romantic melodic lines' },
  { name: 'Los Angeles Azules', role: 'artist', region: 'Latin', genres: ['Cumbia'], era: '1980s-present',
    style: 'Cumbia sonidera with keyboard sweetness',
    tag: 'cumbia sonidera, keyboard melody lines, steady guiro groove, warm brass accents' },
  { name: 'La Sonora Dinamita', role: 'artist', region: 'Latin', genres: ['Cumbia'], era: '1960s-present',
    style: 'Classic Colombian cumbia for the dance floor',
    tag: 'classic Colombian cumbia, brass hooks, guiro and congas, infectious mid-tempo groove' },
  { name: 'Carlos Gardel', role: 'artist', region: 'Latin', genres: ['Pop'], era: '1910s-1930s',
    style: 'The voice that defined tango',
    tag: 'classic tango, bandoneon lead, string ensemble, dramatic rubato phrasing, vintage character' },
  { name: 'Soda Stereo', role: 'artist', region: 'Latin', genres: ['Pop'], era: '1980s-1990s',
    style: 'Argentine rock with new-wave sheen',
    tag: 'Latin alternative rock, chorused guitars, driving new-wave rhythm, atmospheric production' },
  { name: 'Gustavo Cerati', role: 'artist', region: 'Latin', genres: ['Pop'], era: '1980s-2010s',
    style: 'Sophisticated Latin rock and textured songwriting',
    tag: 'Latin alternative rock, layered guitar textures, lush harmonic movement, spacious mix' },
  { name: 'Charly Garcia', role: 'artist', region: 'Latin', genres: ['Pop'], era: '1970s-present',
    style: 'Argentine rock songwriting with restless invention',
    tag: 'Latin rock, piano-driven arrangement, inventive chord movement, bold dynamic shifts' },
  { name: 'Fito Paez', role: 'artist', region: 'Latin', genres: ['Pop'], era: '1980s-present',
    style: 'Piano-led Argentine rock romance',
    tag: 'Latin rock ballad, prominent piano, string arrangement, passionate melodic build' },
  { name: 'Mana', role: 'artist', region: 'Latin', genres: ['Pop'], era: '1980s-present',
    style: 'Mexican rock with reggae and ballad instincts',
    tag: 'Latin rock, clean electric guitar, reggae-tinged rhythm, anthemic chorus' },
  { name: 'Cafe Tacvba', role: 'artist', region: 'Latin', genres: ['Pop'], era: '1990s-present',
    style: 'Mexican alternative rock that refuses one form',
    tag: 'Mexican alternative rock, eclectic instrumentation, folk and electronic blend, inventive arrangement' },
  { name: 'Los Fabulosos Cadillacs', role: 'artist', region: 'Latin', genres: ['Pop', 'Reggae'], era: '1980s-present',
    style: 'Ska and rock with Latin horns',
    tag: 'Latin ska rock, punchy horn section, upstroke guitar, driving danceable rhythm' },
  { name: 'Camaron de la Isla', role: 'artist', region: 'Latin', genres: ['Pop'], era: '1960s-1990s',
    style: 'The voice that modernised flamenco',
    tag: 'flamenco cante, Spanish guitar, palmas hand percussion, raw expressive phrasing' },
  { name: 'Paco de Lucia', role: 'artist', region: 'Latin', genres: ['Pop'], era: '1960s-2010s',
    style: 'Flamenco guitar as virtuoso art form',
    tag: 'flamenco guitar, rapid picado runs, cajon and palmas, jazz-influenced harmony' },
];

export function findInfluence(name: string): Influence | undefined {
  const n = name.trim().toLowerCase();
  return INFLUENCES.find(a => a.name.toLowerCase() === n);
}

export function influencesForGenre(genre: string): Influence[] {
  return INFLUENCES.filter(a => a.genres.includes(genre));
}

/** Grouped for an optgroup picker. Latin first — it is the house sound. */
export function influenceGroups() {
  const of = (region: InfluenceRegion, role: InfluenceRole) =>
    INFLUENCES.filter(a => a.region === region && a.role === role)
      .sort((a, b) => a.name.localeCompare(b.name));
  return [
    { label: 'Latin — Artists', artists: of('Latin', 'artist') },
    { label: 'Latin — Producers', artists: of('Latin', 'producer') },
    { label: 'American — Artists', artists: of('American', 'artist') },
    { label: 'American — Producers', artists: of('American', 'producer') },
  ];
}

// Longest names first so "Juan Luis Guerra" wins over a bare "Juan", and
// bounded by word edges so "Nas" does not fire inside "Natasha".
const MATCHERS = [...INFLUENCES]
  .sort((a, b) => b.name.length - a.name.length)
  .map(inf => ({
    inf,
    re: new RegExp(`(^|[^\\p{L}])${inf.name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}([^\\p{L}]|$)`, 'iu'),
  }));

/**
 * Pull influences out of the user's own words — "a bachata like Romeo Santos"
 * should sound like one without them hunting through a dropdown.
 */
export function detectInfluences(prompt: string, limit = 2): Influence[] {
  if (!prompt) return [];
  const found: Influence[] = [];
  for (const { inf, re } of MATCHERS) {
    if (found.length >= limit) break;
    if (re.test(prompt)) found.push(inf);
  }
  return found;
}
